/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ru.tiis.srv.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.sql.Blob;

import java.util.Date;

/**
 * The base model interface for the Book service. Represents a row in the &quot;TIISBook&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.tiis.srv.model.impl.BookModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.tiis.srv.model.impl.BookImpl}.
 * </p>
 *
 * @author Michael
 * @see Book
 * @see ru.tiis.srv.model.impl.BookImpl
 * @see ru.tiis.srv.model.impl.BookModelImpl
 * @generated
 */
public interface BookModel extends BaseModel<Book> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a book model instance should use the {@link Book} interface instead.
	 */

	/**
	 * Returns the primary key of this book.
	 *
	 * @return the primary key of this book
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this book.
	 *
	 * @param primaryKey the primary key of this book
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the book ID of this book.
	 *
	 * @return the book ID of this book
	 */
	public long getBookId();

	/**
	 * Sets the book ID of this book.
	 *
	 * @param bookId the book ID of this book
	 */
	public void setBookId(long bookId);

	/**
	 * Returns the create date of this book.
	 *
	 * @return the create date of this book
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this book.
	 *
	 * @param createDate the create date of this book
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this book.
	 *
	 * @return the modified date of this book
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this book.
	 *
	 * @param modifiedDate the modified date of this book
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the g drive ID of this book.
	 *
	 * @return the g drive ID of this book
	 */
	@AutoEscape
	public String getGDriveId();

	/**
	 * Sets the g drive ID of this book.
	 *
	 * @param gDriveId the g drive ID of this book
	 */
	public void setGDriveId(String gDriveId);

	/**
	 * Returns the title of this book.
	 *
	 * @return the title of this book
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this book.
	 *
	 * @param title the title of this book
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this book.
	 *
	 * @return the description of this book
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this book.
	 *
	 * @param description the description of this book
	 */
	public void setDescription(String description);

	/**
	 * Returns the google drive link of this book.
	 *
	 * @return the google drive link of this book
	 */
	@AutoEscape
	public String getGoogleDriveLink();

	/**
	 * Sets the google drive link of this book.
	 *
	 * @param googleDriveLink the google drive link of this book
	 */
	public void setGoogleDriveLink(String googleDriveLink);

	/**
	 * Returns the book logo of this book.
	 *
	 * @return the book logo of this book
	 */
	public Blob getBookLogo();

	/**
	 * Sets the book logo of this book.
	 *
	 * @param bookLogo the book logo of this book
	 */
	public void setBookLogo(Blob bookLogo);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ru.tiis.srv.model.Book book);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ru.tiis.srv.model.Book> toCacheModel();

	@Override
	public ru.tiis.srv.model.Book toEscapedModel();

	@Override
	public ru.tiis.srv.model.Book toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}