/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ru.tiis.srv.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Test service. Represents a row in the &quot;TIISTest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.tiis.srv.model.impl.TestModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.tiis.srv.model.impl.TestImpl}.
 * </p>
 *
 * @author Michael
 * @see Test
 * @see ru.tiis.srv.model.impl.TestImpl
 * @see ru.tiis.srv.model.impl.TestModelImpl
 * @generated
 */
public interface TestModel extends BaseModel<Test> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a test model instance should use the {@link Test} interface instead.
	 */

	/**
	 * Returns the primary key of this test.
	 *
	 * @return the primary key of this test
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this test.
	 *
	 * @param primaryKey the primary key of this test
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the test ID of this test.
	 *
	 * @return the test ID of this test
	 */
	public long getTestId();

	/**
	 * Sets the test ID of this test.
	 *
	 * @param testId the test ID of this test
	 */
	public void setTestId(long testId);

	/**
	 * Returns the create date of this test.
	 *
	 * @return the create date of this test
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this test.
	 *
	 * @param createDate the create date of this test
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this test.
	 *
	 * @return the modified date of this test
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this test.
	 *
	 * @param modifiedDate the modified date of this test
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the is book test of this test.
	 *
	 * @return the is book test of this test
	 */
	public boolean getIsBookTest();

	/**
	 * Returns <code>true</code> if this test is is book test.
	 *
	 * @return <code>true</code> if this test is is book test; <code>false</code> otherwise
	 */
	public boolean isIsBookTest();

	/**
	 * Sets whether this test is is book test.
	 *
	 * @param isBookTest the is book test of this test
	 */
	public void setIsBookTest(boolean isBookTest);

	/**
	 * Returns the book ID of this test.
	 *
	 * @return the book ID of this test
	 */
	public long getBookId();

	/**
	 * Sets the book ID of this test.
	 *
	 * @param bookId the book ID of this test
	 */
	public void setBookId(long bookId);

	/**
	 * Returns the content of this test.
	 *
	 * @return the content of this test
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this test.
	 *
	 * @param content the content of this test
	 */
	public void setContent(String content);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ru.tiis.srv.model.Test test);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ru.tiis.srv.model.Test> toCacheModel();

	@Override
	public ru.tiis.srv.model.Test toEscapedModel();

	@Override
	public ru.tiis.srv.model.Test toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}