/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ru.tiis.srv.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TestAttempt service. Represents a row in the &quot;TIISTestAttempt&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.tiis.srv.model.impl.TestAttemptModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.tiis.srv.model.impl.TestAttemptImpl}.
 * </p>
 *
 * @author Michael
 * @see TestAttempt
 * @see ru.tiis.srv.model.impl.TestAttemptImpl
 * @see ru.tiis.srv.model.impl.TestAttemptModelImpl
 * @generated
 */
public interface TestAttemptModel extends BaseModel<TestAttempt> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a test attempt model instance should use the {@link TestAttempt} interface instead.
	 */

	/**
	 * Returns the primary key of this test attempt.
	 *
	 * @return the primary key of this test attempt
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this test attempt.
	 *
	 * @param primaryKey the primary key of this test attempt
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the test ID of this test attempt.
	 *
	 * @return the test ID of this test attempt
	 */
	public long getTestId();

	/**
	 * Sets the test ID of this test attempt.
	 *
	 * @param testId the test ID of this test attempt
	 */
	public void setTestId(long testId);

	/**
	 * Returns the user ID of this test attempt.
	 *
	 * @return the user ID of this test attempt
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this test attempt.
	 *
	 * @param userId the user ID of this test attempt
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this test attempt.
	 *
	 * @return the user uuid of this test attempt
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this test attempt.
	 *
	 * @param userUuid the user uuid of this test attempt
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the start time of this test attempt.
	 *
	 * @return the start time of this test attempt
	 */
	public Date getStartTime();

	/**
	 * Sets the start time of this test attempt.
	 *
	 * @param startTime the start time of this test attempt
	 */
	public void setStartTime(Date startTime);

	/**
	 * Returns the finish time of this test attempt.
	 *
	 * @return the finish time of this test attempt
	 */
	public Date getFinishTime();

	/**
	 * Sets the finish time of this test attempt.
	 *
	 * @param finishTime the finish time of this test attempt
	 */
	public void setFinishTime(Date finishTime);

	/**
	 * Returns the result of this test attempt.
	 *
	 * @return the result of this test attempt
	 */
	public double getResult();

	/**
	 * Sets the result of this test attempt.
	 *
	 * @param result the result of this test attempt
	 */
	public void setResult(double result);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ru.tiis.srv.model.TestAttempt testAttempt);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ru.tiis.srv.model.TestAttempt> toCacheModel();

	@Override
	public ru.tiis.srv.model.TestAttempt toEscapedModel();

	@Override
	public ru.tiis.srv.model.TestAttempt toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}